name: network_logger_custom
description: "A custom network logger for Flutter applications using Dio, featuring a built-in UI for real-time traffic monitoring and inspection."
version: 1.1.0

homepage: https://github.com/Qunnnn/network_logger_custom
repository: https://github.com/Qunnnn/network_logger_custom
issue_tracker: https://github.com/Qunnnn/network_logger_custom/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
